"""
Charts for generate_update11_slides.py — "Auditing My Own Results".

Update 11 is about a methodology audit rather than a new strategy result,
so two of these charts plot measurements taken DURING that audit. Those
values are hardcoded below with their provenance, because they were
produced by code that has since been fixed and cannot be regenerated by
re-running the current codebase. The final chart reads the corrected
study output from results/ like every other chart in this project.

Usage:
    python3 presentations/generate_update11_charts.py [output_dir]
"""
import sys
import glob
from pathlib import Path

import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS = REPO_ROOT / 'results'
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent

SURFACE = '#EDE8E0'
INK = '#2D2D2D'
INK_MUTED = '#6B6B63'
GRID = '#D8D3CA'
RED = '#C62828'
GREEN = '#2E7D32'
ORANGE = '#eb6834'

plt.rcParams.update({
    'font.family': 'sans-serif', 'font.sans-serif': ['Helvetica Neue', 'Arial'],
    'text.color': INK, 'axes.facecolor': SURFACE, 'figure.facecolor': SURFACE,
    'savefig.facecolor': SURFACE,
})

# ── Audit measurements (pre-fix code; cannot be regenerated) ──────────
# Cross-Sectional Reversal, S&P 100, Config A (9 windows), 3yr, 5bps.
# 1. As reported by cross_sectional_sp100.py on 2026-08-24
# 2. Same config re-run 2026-09-08 with end_date PINNED back to 2026-08-24
# 3. Same config re-run 2026-09-08 with the original end=datetime.now()
REPRO_RUNS = [
    ('Reported\n24 Aug', 1.281, 33.3),
    ('Re-run, date\npinned to 24 Aug', 0.423, 44.4),
    ('Re-run\n8 Sep', -2.690, 22.2),
]
# Same 40-symbol config, varying only PYTHONHASHSEED. Pre-fix vs post-fix.
HASHSEED_BEFORE = [('seed 1', 2.0623), ('seed 2', 1.6548)]
HASHSEED_AFTER = [('seed 1', 3.106673), ('seed 2', 3.106673), ('seed 3', 3.106673)]


def latest(pattern):
    files = sorted(glob.glob(str(RESULTS / pattern)))
    if not files:
        raise FileNotFoundError(f"No file matching {pattern} in results/")
    return files[-1]


def chart_reproducibility():
    labels = [r[0] for r in REPRO_RUNS]
    vals = [r[1] for r in REPRO_RUNS]
    cons = [r[2] for r in REPRO_RUNS]

    fig, ax = plt.subplots(figsize=(9.4, 4.8), dpi=200)
    colors = [GREEN if v > 0 else RED for v in vals]
    ax.bar(range(len(vals)), vals, 0.5, color=colors, zorder=3)
    for i, (v, c) in enumerate(zip(vals, cons)):
        ax.annotate(f'{v:+.2f}%\n{c:.0f}% consistent', xy=(i, v),
                    xytext=(0, 8 if v >= 0 else -30), textcoords='offset points',
                    ha='center', fontsize=11, fontweight='bold', color=INK)
    ax.axhline(0, color=INK_MUTED, lw=1)
    lo, hi = min(vals), max(vals)
    ax.set_ylim(lo - abs(lo) * 0.6, hi + abs(hi) * 0.9)
    ax.set_xticks(range(len(labels)), labels, fontsize=11)
    ax.set_ylabel('Mean out-of-sample return per window')
    ax.grid(axis='y', color=GRID, lw=0.8)
    ax.spines[['top', 'right', 'left']].set_visible(False)
    ax.tick_params(length=0)
    fig.tight_layout()
    fig.savefig(OUT / 'chart_u11_repro.png', bbox_inches='tight')
    plt.close(fig)
    print('reproducibility chart done')


def chart_determinism():
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.0, 4.6), dpi=200,
                                    gridspec_kw={'width_ratios': [2, 3]})
    for ax, data, title, color in (
        (ax1, HASHSEED_BEFORE, 'Before the fix', RED),
        (ax2, HASHSEED_AFTER, 'After the fix', GREEN),
    ):
        ax.set_facecolor(SURFACE)
        labels = [d[0] for d in data]
        vals = [d[1] for d in data]
        ax.bar(range(len(vals)), vals, 0.45, color=color, zorder=3)
        for i, v in enumerate(vals):
            ax.annotate(f'{v:+.4f}%', xy=(i, v), xytext=(0, 6), textcoords='offset points',
                        ha='center', fontsize=10.5, fontweight='bold', color=INK)
        ax.set_xticks(range(len(labels)), labels, fontsize=11)
        ax.set_ylim(0, 3.9)
        ax.set_title(title, fontsize=13, fontweight='bold', color=INK)
        ax.grid(axis='y', color=GRID, lw=0.8)
        ax.spines[['top', 'right', 'left']].set_visible(False)
        ax.tick_params(length=0)
    ax1.set_ylabel('Mean out-of-sample return')
    fig.suptitle('Identical code, identical data, identical dates — only Python\'s hash seed differs',
                 fontsize=11.5, color=INK_MUTED, style='italic', y=1.02)
    fig.tight_layout()
    fig.savefig(OUT / 'chart_u11_determinism.png', bbox_inches='tight')
    plt.close(fig)
    print('determinism chart done')


def chart_corrected():
    df = pd.read_csv(latest('cross_sectional_corrected_*.csv'))
    df = df[~df['market'].isna()]
    labels, a_vals, b_vals, robust_flags = [], [], [], []
    for _, r in df.iterrows():
        mkt = 'S&P 100' if 'S&P' in r['market'] else 'Hang Seng'
        strat = 'Reversal' if 'Reversal' in r['strategy'] else 'Momentum'
        # The cost regime differs by market (no calibrated US fee exists), so
        # label it: without this the chart invites a false like-for-like read.
        cost = 'no fees' if 'zero' in str(r.get('commission', '')) else 'real fees'
        labels.append(f'{mkt}\n{strat}\n({cost})')
        a_vals.append(r['config_a_oos'])
        b_vals.append(r['config_b_oos'])
        robust_flags.append(bool(r['robust']))

    fig, ax = plt.subplots(figsize=(10.2, 4.8), dpi=200)
    x = range(len(labels))
    w = 0.34
    ax.bar([i - w / 2 for i in x], a_vals, w, color=INK_MUTED, zorder=3, label='Config A (9 windows)')
    ax.bar([i + w / 2 for i in x], b_vals, w, color=ORANGE, zorder=3, label='Config B (15 windows)')
    for i, v in enumerate(a_vals):
        ax.annotate(f'{v:+.2f}%', xy=(i - w / 2, v), xytext=(0, 6 if v >= 0 else -15),
                    textcoords='offset points', ha='center', fontsize=10, fontweight='bold', color=INK)
    for i, v in enumerate(b_vals):
        ax.annotate(f'{v:+.2f}%', xy=(i + w / 2, v), xytext=(0, 6 if v >= 0 else -15),
                    textcoords='offset points', ha='center', fontsize=10, fontweight='bold', color=INK)
    ax.axhline(0, color=INK_MUTED, lw=1)
    lo, hi = min(a_vals + b_vals), max(a_vals + b_vals)
    pad = max(0.25, (hi - lo) * 0.30)
    ax.set_ylim(lo - pad, hi + pad)

    # Mark the one combination that met the standard, so the chart states
    # its own verdict rather than leaving it to be inferred from the bars.
    for i, is_robust in enumerate(robust_flags):
        if is_robust:
            ax.annotate('VALIDATED', xy=(i, hi + pad * 0.55), ha='center',
                        fontsize=12.5, fontweight='bold', color=GREEN)
            ax.axvspan(i - 0.45, i + 0.45, color=GREEN, alpha=0.07, zorder=0)

    ax.set_xticks(list(x), labels, fontsize=10)
    ax.set_ylabel('Mean out-of-sample return per window')
    ax.grid(axis='y', color=GRID, lw=0.8)
    ax.spines[['top', 'right', 'left']].set_visible(False)
    ax.tick_params(length=0)
    ax.legend(loc='best', frameon=False, fontsize=9.5)
    fig.tight_layout()
    fig.savefig(OUT / 'chart_u11_corrected.png', bbox_inches='tight')
    plt.close(fig)
    print('corrected-results chart done —', list(zip(labels, a_vals, b_vals)))


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    chart_reproducibility()
    chart_determinism()
    try:
        chart_corrected()
    except FileNotFoundError as e:
        print("SKIPPED corrected chart (re-run still in progress):", e)


def chart_cost_sensitivity():
    """The one validated result, across three cost assumptions."""
    df = pd.read_csv(latest('cross_sectional_cost_sensitivity_*.csv'))
    labels = [l.replace(' (', '\n(') for l in df['label']]

    fig, ax = plt.subplots(figsize=(10.2, 4.9), dpi=200)
    x = range(len(df))
    w = 0.34
    ax.bar([i - w / 2 for i in x], df['config_a_oos'], w, color=INK_MUTED, zorder=3,
           label='Config A (9 windows)')
    ax.bar([i + w / 2 for i in x], df['config_b_oos'], w, color=ORANGE, zorder=3,
           label='Config B (15 windows)')
    for i, r in df.iterrows():
        for xp, v in ((i - w / 2, r['config_a_oos']), (i + w / 2, r['config_b_oos'])):
            ax.annotate(f'{v:+.2f}%', xy=(xp, v), xytext=(0, 6 if v >= 0 else -15),
                        textcoords='offset points', ha='center', fontsize=10,
                        fontweight='bold', color=INK)
    ax.axhline(0, color=INK_MUTED, lw=1)
    lo, hi = min(df['config_b_oos'].min(), df['config_a_oos'].min()), df['config_a_oos'].max()
    pad = (hi - lo) * 0.32
    ax.set_ylim(lo - pad, hi + pad)

    for i, r in df.iterrows():
        ok = bool(r['robust'])
        ax.annotate('VALIDATES' if ok else 'fails', xy=(i, hi + pad * 0.45), ha='center',
                    fontsize=12 if ok else 11, fontweight='bold',
                    color=GREEN if ok else RED)
        if ok:
            ax.axvspan(i - 0.45, i + 0.45, color=GREEN, alpha=0.07, zorder=0)

    ax.set_xticks(list(x), labels, fontsize=10.5)
    ax.set_xlabel('Commission assumed, per side', fontsize=11)
    ax.set_ylabel('Mean out-of-sample return per window')
    ax.grid(axis='y', color=GRID, lw=0.8)
    ax.spines[['top', 'right', 'left']].set_visible(False)
    ax.tick_params(length=0)
    ax.legend(loc='lower left', frameon=False, fontsize=9.5)
    fig.tight_layout()
    fig.savefig(OUT / 'chart_u11_costsens.png', bbox_inches='tight')
    plt.close(fig)
    print('cost-sensitivity chart done')


if True:
    OUT.mkdir(parents=True, exist_ok=True)
    try:
        chart_cost_sensitivity()
    except FileNotFoundError as e:
        print("SKIPPED cost-sensitivity chart:", e)
